// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelAI.Data;

#nullable disable

namespace TravelAI.Data.Migrations
{
    [DbContext(typeof(TravelAIDbContext))]
    [Migration("20260618205124_AddIsAdmin")]
    partial class AddIsAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelAI.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Adventure",
                            City = "Cairo",
                            CountryId = 1,
                            Description = "Explore the ancient wonders with expert guide",
                            DurationHours = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800",
                            IsFeatured = true,
                            IsPopular = true,
                            Name = "Pyramids of Giza Tour",
                            Price = 85m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 5432
                        },
                        new
                        {
                            Id = 2,
                            Category = "Adventure",
                            City = "Fujiyoshida",
                            CountryId = 2,
                            Description = "Guided trek to Japan's iconic peak",
                            DurationHours = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800",
                            IsFeatured = true,
                            IsPopular = true,
                            Name = "Mount Fuji Hiking",
                            Price = 120m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 3211
                        },
                        new
                        {
                            Id = 3,
                            Category = "Museums",
                            City = "Paris",
                            CountryId = 3,
                            Description = "Paris highlights with skip-the-line access",
                            DurationHours = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
                            IsFeatured = true,
                            IsPopular = true,
                            Name = "Eiffel Tower & Louvre",
                            Price = 95m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 8765
                        },
                        new
                        {
                            Id = 4,
                            Category = "Food",
                            City = "Bangkok",
                            CountryId = 4,
                            Description = "Learn authentic Thai cuisine from a local chef",
                            DurationHours = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800",
                            IsFeatured = true,
                            IsPopular = true,
                            Name = "Thai Cooking Masterclass",
                            Price = 55m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 2134
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cultural",
                            City = "Venice",
                            CountryId = 5,
                            Description = "Classic gondola ride through Venice canals",
                            DurationHours = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=800",
                            IsFeatured = true,
                            IsPopular = true,
                            Name = "Venice Gondola & Rialto",
                            Price = 75m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 4321
                        },
                        new
                        {
                            Id = 6,
                            Category = "Adventure",
                            City = "Male",
                            CountryId = 7,
                            Description = "Discover vibrant coral reefs and marine life",
                            DurationHours = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
                            IsFeatured = true,
                            IsPopular = true,
                            Name = "Maldives Snorkeling Safari",
                            Price = 180m,
                            Rating = 5.0,
                            ReviewCount = 1876
                        });
                });

            modelBuilder.Entity("TravelAI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelAI.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("TravelAI.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageBudgetPerDay")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageBudgetPerDay = 80m,
                            Code = "EG",
                            Continent = "Africa",
                            Description = "Land of the Pharaohs",
                            ImageUrl = "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800",
                            IsPopular = true,
                            Name = "Egypt",
                            NameAr = "مصر",
                            NameEs = "Egipto",
                            NameFr = "Égypte",
                            NameRu = "Египет",
                            NameTr = "Mısır",
                            NameZh = "埃及",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            AverageBudgetPerDay = 150m,
                            Code = "JP",
                            Continent = "Asia",
                            Description = "Land of the Rising Sun",
                            ImageUrl = "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
                            IsPopular = true,
                            Name = "Japan",
                            NameAr = "اليابان",
                            NameEs = "Japón",
                            NameFr = "Japon",
                            NameRu = "Япония",
                            NameTr = "Japonya",
                            NameZh = "日本",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            AverageBudgetPerDay = 180m,
                            Code = "FR",
                            Continent = "Europe",
                            Description = "City of Light and Art",
                            ImageUrl = "https://images.unsplash.com/photo-1499856871958-5b9357976b82?w=800",
                            IsPopular = true,
                            Name = "France",
                            NameAr = "فرنسا",
                            NameEs = "Francia",
                            NameFr = "France",
                            NameRu = "Франция",
                            NameTr = "Fransa",
                            NameZh = "法国",
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            AverageBudgetPerDay = 70m,
                            Code = "TH",
                            Continent = "Asia",
                            Description = "Land of Smiles",
                            ImageUrl = "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800",
                            IsPopular = true,
                            Name = "Thailand",
                            NameAr = "تايلاند",
                            NameEs = "Tailandia",
                            NameFr = "Thaïlande",
                            NameRu = "Таиланд",
                            NameTr = "Tayland",
                            NameZh = "泰国",
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            AverageBudgetPerDay = 160m,
                            Code = "IT",
                            Continent = "Europe",
                            Description = "Eternal City & Cuisine",
                            ImageUrl = "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800",
                            IsPopular = true,
                            Name = "Italy",
                            NameAr = "إيطاليا",
                            NameEs = "Italia",
                            NameFr = "Italie",
                            NameRu = "Италия",
                            NameTr = "İtalya",
                            NameZh = "意大利",
                            Rating = 5
                        },
                        new
                        {
                            Id = 6,
                            AverageBudgetPerDay = 200m,
                            Code = "US",
                            Continent = "Americas",
                            Description = "Land of Opportunities",
                            ImageUrl = "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800",
                            IsPopular = true,
                            Name = "USA",
                            NameAr = "الولايات المتحدة",
                            NameEs = "EE.UU.",
                            NameFr = "États-Unis",
                            NameRu = "США",
                            NameTr = "ABD",
                            NameZh = "美国",
                            Rating = 5
                        },
                        new
                        {
                            Id = 7,
                            AverageBudgetPerDay = 350m,
                            Code = "MV",
                            Continent = "Asia",
                            Description = "Tropical Paradise",
                            ImageUrl = "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800",
                            IsPopular = true,
                            Name = "Maldives",
                            NameAr = "جزر المالديف",
                            NameEs = "Maldivas",
                            NameFr = "Maldives",
                            NameRu = "Мальдивы",
                            NameTr = "Maldivler",
                            NameZh = "马尔代夫",
                            Rating = 5
                        },
                        new
                        {
                            Id = 8,
                            AverageBudgetPerDay = 90m,
                            Code = "TR",
                            Continent = "Europe",
                            Description = "Where East Meets West",
                            ImageUrl = "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800",
                            IsPopular = true,
                            Name = "Turkey",
                            NameAr = "تركيا",
                            NameEs = "Turquía",
                            NameFr = "Turquie",
                            NameRu = "Турция",
                            NameTr = "Türkiye",
                            NameZh = "土耳其",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("TravelAI.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AirlineLogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDirectFlight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SeatsAvailable")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Airline = "Emirates",
                            AirlineCode = "EK",
                            AirlineLogo = "",
                            ArrivalTime = new DateTime(2026, 7, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Class = "Economy",
                            DepartureTime = new DateTime(2026, 7, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Cairo",
                            DestinationCode = "CAI",
                            DurationMinutes = 150,
                            IsDirectFlight = true,
                            IsFeatured = true,
                            Origin = "Dubai",
                            OriginCode = "DXB",
                            Price = 320m,
                            SeatsAvailable = 42
                        },
                        new
                        {
                            Id = 2,
                            Airline = "Qatar Airways",
                            AirlineCode = "QR",
                            AirlineLogo = "",
                            ArrivalTime = new DateTime(2026, 7, 21, 7, 0, 0, 0, DateTimeKind.Utc),
                            Class = "Business",
                            DepartureTime = new DateTime(2026, 7, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Tokyo",
                            DestinationCode = "NRT",
                            DurationMinutes = 720,
                            IsDirectFlight = false,
                            IsFeatured = true,
                            Origin = "Doha",
                            OriginCode = "DOH",
                            Price = 890m,
                            SeatsAvailable = 8
                        },
                        new
                        {
                            Id = 3,
                            Airline = "Air France",
                            AirlineCode = "AF",
                            AirlineLogo = "",
                            ArrivalTime = new DateTime(2026, 7, 18, 13, 0, 0, 0, DateTimeKind.Utc),
                            Class = "Economy",
                            DepartureTime = new DateTime(2026, 7, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            Destination = "New York",
                            DestinationCode = "JFK",
                            DurationMinutes = 510,
                            IsDirectFlight = true,
                            IsFeatured = true,
                            Origin = "Paris",
                            OriginCode = "CDG",
                            Price = 650m,
                            SeatsAvailable = 27
                        },
                        new
                        {
                            Id = 4,
                            Airline = "Turkish Airlines",
                            AirlineCode = "TK",
                            AirlineLogo = "",
                            ArrivalTime = new DateTime(2026, 7, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            Class = "Economy",
                            DepartureTime = new DateTime(2026, 7, 22, 1, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Bangkok",
                            DestinationCode = "BKK",
                            DurationMinutes = 600,
                            IsDirectFlight = false,
                            IsFeatured = true,
                            Origin = "Istanbul",
                            OriginCode = "IST",
                            Price = 540m,
                            SeatsAvailable = 33
                        });
                });

            modelBuilder.Entity("TravelAI.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasPool")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSpa")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLuxury")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<double>("Stars")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            City = "Cairo",
                            CountryId = 1,
                            Description = "Iconic 5-star hotel overlooking the Nile River",
                            HasPool = true,
                            HasSpa = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
                            IsFeatured = true,
                            IsLuxury = true,
                            Name = "Nile Ritz-Carlton Cairo",
                            PricePerNight = 320m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 2341,
                            Stars = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            City = "Tokyo",
                            CountryId = 2,
                            Description = "Luxury high-rise with panoramic city views",
                            HasPool = true,
                            HasSpa = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
                            IsFeatured = true,
                            IsLuxury = true,
                            Name = "Park Hyatt Tokyo",
                            PricePerNight = 580m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 1876,
                            Stars = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            City = "Paris",
                            CountryId = 3,
                            Description = "Palace hotel in the heart of Paris since 1835",
                            HasPool = false,
                            HasSpa = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
                            IsFeatured = true,
                            IsLuxury = true,
                            Name = "Hôtel Le Meurice Paris",
                            PricePerNight = 750m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 3201,
                            Stars = 5.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "",
                            City = "Bangkok",
                            CountryId = 4,
                            Description = "Serene riverside retreat with Thai architecture",
                            HasPool = true,
                            HasSpa = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
                            IsFeatured = true,
                            IsLuxury = true,
                            Name = "Anantara Riverside Bangkok",
                            PricePerNight = 210m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 1654,
                            Stars = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "",
                            City = "Florence",
                            CountryId = 5,
                            Description = "Renaissance palace turned luxury hotel",
                            HasPool = true,
                            HasSpa = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800",
                            IsFeatured = true,
                            IsLuxury = true,
                            Name = "Four Seasons Florence",
                            PricePerNight = 680m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 2109,
                            Stars = 5.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "",
                            City = "Noonu Atoll",
                            CountryId = 7,
                            Description = "Overwater villas in pristine turquoise lagoon",
                            HasPool = true,
                            HasSpa = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1439066290691-daf3a565efed?w=800",
                            IsFeatured = true,
                            IsLuxury = true,
                            Name = "Soneva Jani Maldives",
                            PricePerNight = 1800m,
                            Rating = 5.0,
                            ReviewCount = 987,
                            Stars = 5.0
                        });
                });

            modelBuilder.Entity("TravelAI.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("TravelAI.Models.Activity", b =>
                {
                    b.HasOne("TravelAI.Models.Country", "Country")
                        .WithMany("Activities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelAI.Models.ChatMessage", b =>
                {
                    b.HasOne("TravelAI.Models.AppUser", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAI.Models.Hotel", b =>
                {
                    b.HasOne("TravelAI.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelAI.Models.Subscription", b =>
                {
                    b.HasOne("TravelAI.Models.AppUser", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("TravelAI.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAI.Models.AppUser", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("TravelAI.Models.Country", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
